apiVersion: v1
kind: Service
metadata:
  labels:
    app: hrm-identity
  name: hrm-identity
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hrm-identity
  type: ClusterIP
