apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hrm-identity-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hrm-identity
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80